FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*",  "npm-shrinkwrap.json*","tsconfig.json","./src/prisma", "./"]

RUN npm install -g @nestjs/cli
RUN npm install --production --silent && mv node_modules ../

COPY . .
EXPOSE 3000
RUN chown -R node /usr/src/app
RUN npx prisma generate
USER node
CMD ["npm", "start"]
